logger:
  file:
    path: /var/log/open5gs/nrf.log

global:

nrf:
  serving:
    - plmn_id:
        mcc: 262
        mnc: 02
  sbi:
    server:
      - address: nrf.5gc.mnc002.mcc262.3gppnetwork.org
        port: 80
